### ISSUE TITLE
Get-GPOUnlinked function not finding all links

### ISSUE THREAD

**Issue by MarkDarwin** [Saggiehaim/Powershell#5]
The Get-GPOUnlinked function doesn't take into account GP's which are linked to AD Sites.

If you run this you can get the GUIDs for site linked GP's but I'm not sure how best to combine this with your code:
Get-ADObject -LDAPFilter '(objectClass=site)' `
 -SearchBase "CN=Sites,$((Get-ADRootDSE).configurationNamingContext)" `
 -SearchScope OneLevel -Properties name, distinguishedName, gPLink, gPOptions

**Comment by Saggiehaim** [comment]
Hey, 
thanks for the feedback.
The function doesn't rely on GPO Links. The cmdlet Get-GPO -all, retrieve all GPO's, regardless of their link.
In addition, you can't create a new GPO **directly** on a site, you can only link an existing GPO.

I will be happy to get more information about your issue, maybe I miss understood it.

**Comment by MarkDarwin** [comment]
Apologies, I typed Disabled instead of GPOUnlinked. (Have edited the original comment)

What I was trying to do was list all unlinked GPs but from the returned list I noticed that some were indeed linked to sites.

Does that make more sense?

**Comment by Saggiehaim** [comment]
Yeah, It makes much more sense 😃
To be honest, I didn't took this scenario into consideration.

Working on it, will update ASAP.
Thanks again!

**Comment by Saggiehaim** [comment]
Hey,
A new version of Get-GPOUnlinked has been updated. 
I made some tests and it looked good, Waiting for your feedback.

Thanks!

**Comment by MarkDarwin** [comment]
Tested it again today and all working as expected.  Thanks for the update.
